name: Achievement Jar Build and Deploy to S3

on:
  push:
    branches:
      - feature-ci-cd  # Set your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      bucket: ${{ steps.set_env.outputs.bucket }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20' # Set the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build -- --prod

    - name: Archive production artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist/your-angular-app-name # Replace with the path to your Angular app's build output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dist

    - name: Deploy to AWS S3
      run: |
        aws s3 sync ./dist s3://${{ needs.build.outputs.bucket }} --no-progress --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
