name: Achievement Jar Build and Deploy to S3

on:
  push:
    branches:
      - feature-ci-cd  # Set your deployment branch

env:
  NODE_VERSION: '20.x' # Set the Node.js version
  BUILD_PATH: './dist/achievement-jar' # Replace with the path to your Angular app's build output

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      bucket: ${{ secrets.S3_BUCKET }} # Assuming you store your bucket name in secrets

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build --prod

    - name: Archive production artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ env.BUILD_PATH }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist

    - name: Deploy to AWS S3
      run: |
        aws s3 sync ${{ env.BUILD_PATH }} s3://${{ needs.build.outputs.bucket }} --no-progress --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
